apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-db
  labels:
    app: sql-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sql-db
  template:
    metadata:
      labels:
        app: sql-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image.repository }}
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.postgresUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.postgresPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.postgresDatabase }}