apiVersion: v1
kind: Service
metadata:
  name: sql-db
  labels:
    app: sql-db
spec:
  selector:
    app: sql-db
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
  type: {{ .Values.postgres.service.type }}