apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver
  namespace: argocd-ns
spec:
  project: default
  source:
    repoURL: https://gitlab.com/projects_mvbs/d_a_k.git
    targetRevision: main
    path: Kind/charts/dev
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
