kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# networking:
#   apiServerAddress: 127.0.0.1
nodes:
- role: control-plane
- role: worker
  labels:
    tier: frontend
- role: worker
  labels:
    tier: backend

## https://kind.sigs.k8s.io/docs/user/configuration ##