apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-aws-s3
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-ns
      name: aws-creds
      key: creds