---
- name: Install needed packages / Helm repo tasks / Kind cluster creation and configuration
  hosts: localhost
  become: yes # exec as root
  tasks:
    - name: Update Container Packages
      apt:
        update_cache: yes

    - name: Download Kind binary
      get_url:
        url: "https://github.com/kubernetes-sigs/kind/releases/download/v0.12.0/kind-linux-amd64"
        dest: "/usr/local/bin/kind"
        mode: '0755'

    - name: Download kubectl binary
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/amd64/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: '0755'
      
    - name: Download Helm binary
      get_url:
        url: "https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz"
        dest: "/tmp/helm.tar.gz"

    - name: Extract Helm binary
      ansible.builtin.unarchive:
        src: "/tmp/helm.tar.gz"
        dest: "/tmp/"

    - name: Move Helm binary to /usr/local/bin/
      ansible.builtin.copy:
        src: "/tmp/linux-amd64/helm"
        dest: "/usr/local/bin/helm"
        mode: '0755'

    # Helm repo tasks
    - name: Crossplane Helm Repo
      ansible.builtin.command: helm repo add crossplane-stable https://charts.crossplane.io/stable

    # - name: Ingress-Nginx Helm Repo
    #   ansible.builtin.command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    # - name: Redis/SQL/Nginx Helm Repo
    #   ansible.builtin.command: helm repo add bitnami https://charts.bitnami.com/bitnami

        # - name: Prometheus Helm Repo
    #   ansible.builtin.command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    # - name: Fluent Bit Helm Repo
    #   ansible.builtin.command: helm repo add fluent https://fluent.github.io/helm-charts

    # - name: Kasten Helm Repo
    #   ansible.builtin.command: helm repo add kasten https://charts.kasten.io/

    # - name: Strimzi Helm Repo
    #   ansible.builtin.command: helm repo add strimzi https://strimzi.io/charts/

    - name: Search Helm Charts
      ansible.builtin.command: helm search repo

    - name: Update Helm Repositories
      ansible.builtin.command: helm repo update

    - name: Create Kind cluster
      ansible.builtin.command: kind create cluster --config=../kind-config/kind-config.yaml

    # Create namespaces on cluster environment
    - name: Create namespaces
      ansible.builtin.command: kubectl create namespace {{ item }}
      loop:
        - crossplane-ns

    # Helm Installation
    - name: Helm installing crossplane...
      ansible.builtin.command: helm install my-crossplane crossplane-stable/crossplane --namespace crossplane-ns

    # - name: Helm installing nginx...
    #   ansible.builtin.command: helm install my-nginx bitnami/nginx --namespace webserver-ns

    # - name: Helm installing postgreSQL...
    #   ansible.builtin.command: helm install my-postgresql bitnami/postgresql --namespace database-ns

    # - name: Install Ingress-Nginx using Helm ERROR
    #   ansible.builtin.command: helm install my-ingress-nginx ingress-nginx/ingress-nginx --dry-run --debug --namespace nginxingress-ns

    # - name: Helm installing Prometheus...
    #   ansible.builtin.command: helm install my-prometheus prometheus-community/prometheus --namespace monitoring-ns

    # - name: Helm installing Fluent Bit...
    #   ansible.builtin.command: helm install my-fluent-bit fluent/fluent-bit --namespace logs-ns

    # - name: Helm installing Redis...
    #   ansible.builtin.command: helm install my-redis bitnami/redis --namespace cache-ns

    # - name: Helm installing Kasten... ERROR
    #   ansible.builtin.command: helm install my-kasten kasten/k10 --namespace kasten-ns

    # - name: Helm installing Strimzi Kafka Operator...
    #   ansible.builtin.command: helm install my-strimzi strimzi/strimzi-kafka-operator --namespace kafka-ns

  #  Cluster configuration
    - name: Installing cluster configuration...
      shell: ../kind-config/add_aws_bucket.sh