apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.deployment.name }}
  namespace: {{ .Values.nginx.ingress.namespace }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.nginx.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.deployment.image }}
          ports:
            - containerPort: {{ .Values.nginx.service.ports.port1 }}
            - containerPort: {{ .Values.nginx.service.ports.port2 }}
          env:
          - name: ENV1
            value: "Hello from the environment variable"
          - name: ENV2
            value: "It is simple"
          command: ['sh']
          args: ['-c', 'printenv']